-- ==============================================================
-- SCRIPT COMPLETO: Cargar datos de prueba para Comisiones
-- Ejecutar conectado como CONSULTORES en SQL Developer
-- ==============================================================

-- Limpiar tablas existentes
TRUNCATE TABLE DETALLE_COMISIONES_AUDITORIAS_MES;
TRUNCATE TABLE RESUMEN_COMISIONES_AUDIT_MES;

-- Insertar datos de prueba REALISTAS
INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '11111111-1', 'Juan Pérez', 'Auditor Interno',
    150000, 25000, 50000, 60000, 285000, 285000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '18765432-1', 'María González', 'Consultor TI',
    120000, 20000, 30000, 22000, 192000, 192000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '20458761-2', 'Carlos López', 'Auditor Externo',
    180000, 45000, 60000, 40000, 325000, 325000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '15623487-3', 'Ana Silva', 'Especialista Cybersecurity',
    220000, 45000, 65000, 50000, 380000, 380000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '19876543-4', 'Roberto Díaz', 'Auditor Financiero',
    180000, 35000, 55000, 40000, 310000, 310000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '21345678-5', 'Carmen Rojas', 'Consultor SAP',
    250000, 60000, 70000, 60000, 440000, 440000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '22456789-6', 'Pedro Martínez', 'Auditor de Sistemas',
    160000, 30000, 45000, 35000, 270000, 270000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '23567890-7', 'Laura Fernández', 'Consultor Oracle',
    280000, 65000, 75000, 65000, 485000, 485000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '24678901-8', 'Diego Contreras', 'Contador',
    150000, 35000, 45000, 45000, 275000, 275000
);

INSERT INTO DETALLE_COMISIONES_AUDITORIAS_MES (
    MES_PROCESO, ANNO_PROCESO, RUN_AUDITOR, NOMBRE_AUDITOR, NOMBRE_PROFESION,
    COMISION_TOTAL_AUDIT, COMISION_MONTO_AUDIT, COMISION_PROF_CRITICA, 
    COMISION_EXTRA, TOTAL_COMISION_AUDIT, TOTAL_COMISION_EMPRESA
) VALUES (
    9, 2025, '25789012-9', 'Sofía Herrera', 'Tester',
    50, 25, 15, 10, 100, 100
);

COMMIT;

-- ==============================================================
-- EJECUTAR EL PROCEDIMIENTO PARA GENERAR EL RESUMEN
-- ==============================================================
SET SERVEROUTPUT ON;
BEGIN
    CALCULAR_COMISIONES_MES(9, 2025);
END;
/

-- ==============================================================
-- VERIFICAR LOS DATOS CARGADOS
-- ==============================================================
-- Ver datos en detalle
SELECT RUN_AUDITOR, NOMBRE_PROFESION, TOTAL_COMISION_AUDIT
FROM DETALLE_COMISIONES_AUDITORIAS_MES
ORDER BY TOTAL_COMISION_AUDIT DESC;

-- Ver resumen generado
SELECT * FROM RESUMEN_COMISIONES_AUDIT_MES 
ORDER BY MONTO_TOTAL_COMISIONES DESC;

-- Conteo final
SELECT 
    (SELECT COUNT(*) FROM DETALLE_COMISIONES_AUDITORIAS_MES) as "Total Detalle",
    (SELECT COUNT(*) FROM RESUMEN_COMISIONES_AUDIT_MES) as "Total Resumen"
FROM DUAL;